export class Constant {

    public static Corousals = [
      {imagepath:"../../../assets/img/slider/1.jpg"},
      {imagepath:"../../../assets/img/slider/2.jpg"},
      {imagepath:"../../../assets/img/slider/3.jpg"},
      {imagepath:"../../../assets/img/slider/4.jpg"}
    ]
    public static FoodType = [
        {value:'veg', viewValue:'Veg' },
        {value:'non-veg', viewValue:'Non-Veg' }
    ];

    public static Cuisines = [
        {value:'indian',viewValue: 'Indian'},
        {value:'chinese',viewValue: 'Chinese'}
    ];

    public static Categories = [
        // Veg Menu
        // {cuisineType:'indian', category:'Appetisers'},
        {foodType:'veg',cuisineType:'indian', category:'Appetisers'},
        {foodType:'veg',cuisineType:'indian', category:'Main Course'},
        {foodType:'veg',cuisineType:'indian', category:'Biryani'},
        {foodType:'veg',cuisineType:'indian', category:'Breads'},
        {foodType:'veg',cuisineType:'indian', category:'Desserts'},

        {foodType:'veg',cuisineType:'chinese', category:'Appetisers'},
        {foodType:'veg',cuisineType:'chinese', category:'Sushi'},
        {foodType:'veg',cuisineType:'chinese', category:'Rice And Noodles'},
        {foodType:'veg',cuisineType:'chinese', category:'Main Course'},
        // Non Veg Menu
        {foodType:'non-veg',cuisineType:'indian', category:'Appetisers'},
        {foodType:'non-veg',cuisineType:'indian', category:'Appetisers Sea Food'},
        {foodType:'non-veg',cuisineType:'indian', category:'Main Course'},
        {foodType:'non-veg',cuisineType:'indian', category:'Sea Food Main Course'},
        {foodType:'non-veg',cuisineType:'indian', category:'Biryani'},

        {foodType:'non-veg',cuisineType:'chinese', category:'Appetisers'},
        {foodType:'non-veg',cuisineType:'chinese', category:'Appetisers Sea Food'},
        {foodType:'non-veg',cuisineType:'chinese', category:'Sea Food Main Course'},
        {foodType:'non-veg',cuisineType:'chinese', category:'Rice And Noodles'},
        {foodType:'non-veg',cuisineType:'chinese', category:'Main Course'},
    ]

    public static Variation = [
        { dishId:17, dish:"Fish Soya Chili", variation:[{name:"Basa",price:"900"},{name:"Ravas",price:"1050"}], variant:[]},
        { dishId:19, dish:"Fish Basil Tamarind", variation:[{name:"Basa",price:"850"},{name:"Ravas",price:"1300"}], variant:[]},
        { dishId:69, dish:"Fish Koliwada", variation:[{name:"Basa",price:"1050"},{name:"Ravas",price:"1540"}], variant:[]},
        { dishId:70, dish:"Fish Tikka", variation:[{name:"Basa",price:"1050"},{name:"Ravas",price:"1540"}], variant:[]},
        { dishId:92, dish:"Fish Goan Curry", variation:[{name:"Surmai",price:"1405"},{name:"Ravas",price:"1540"}], variant:[]},
        { dishId:94, dish:"Prawns", variation:[{name:"Kadai",price:"1100"},{name:"Goan Curry",price:"1491"}], variant:[]},
        { dishId:101, dish:"Roti", variation:[{name:"Plain",price:"25"},{name:"Butter",price:"35"}], variant:[]},
        { dishId:102, dish:"Naan", variation:[{name:"Plain",price:"30"},{name:"Butter",price:"40"}], variant:[]},
        { dishId:103, dish:"Kulcha", variation:[{name:"Plain",price:"35"},{name:"Butter",price:"45"}], variant:[]},
        { dishId:104, dish:"Garlic Naan", variation:[{name:"Plain",price:"35"},{name:"Butter",price:"45"}], variant:[]},
        { dishId:106, dish:"Paneer Paratha", variation:[{name:"Plain",price:"50"},{name:"Butter",price:"60"}], variant:[]},
        { dishId:107, dish:"Cheese Garlic Naan", variation:[{name:"Plain",price:"55"},{name:"Butter",price:"65"}], variant:[]},

        { dishId:105, dish:"Stuffed Paratha", variation:[{name:"Plain",price:"40"},{name:"Butter",price:"50"}], variant:["Onion","Aloo","Gobi","Mix"]},
        { dishId:44, dish:"Thai Curry", variation:[{name:"Fish",price:"1300"},{name:"Prawns",price:"1400"}], variant:["Red","Yellow","Green"]},

        { dishId:41, dish:"Paneer (Choice of Sauce)", variation:[], variant:["Black Bean","Hot Garlic","Hunan","Sichuan","Oyster"]},
        { dishId:43, dish:"Chicken Thai Curry", variation:[], variant:["Red","Yellow","Green"]},
        { dishId:79, dish:"Paneer", variation:[], variant:["Kadai","Butter Masala","Lababdar"]},
        { dishId:80, dish:"Yellow Dal", variation:[], variant:["Fry","Tadka"]},
        { dishId:112, dish:"Vegetable Thai Curry", variation:[], variant:["Red","Yellow","Green"]},
        { dishId:113, dish:"Vegetables (Choice of Sauce)", variation:[], variant:["Black Bean","Hot Garlic","Hunan","Sichuan","Oyster"]},
        { dishId:114, dish:"Chicken (Choice of Sauce)", variation:[], variant:["Black Bean","Hot Garlic","Hunan","Sichuan","Oyster"]},
        { dishId:115, dish:"Tandoori Platter", variation:[], variant:["Mushroom","Baby Corn","Baby Potato","Gobi"]},
        { dishId:116, dish:"Pulao", variation:[], variant:["GreenPeas","Pilaf","Veg"]},
        { dishId:117, dish:"Fish (Choice of Sauce)", variation:[], variant:["Black Bean","Hot Garlic","Hunan","Sichuan","Oyster"]},
        { dishId:118, dish:"Prawns (Choice of Sauce)", variation:[], variant:["Black Bean","Hot Garlic","Hunan","Sichuan","Oyster"]},
    ]
    // public static Dishes = [
    //     {foodType:'veg',cuisineType:'indian', category:'Appetisers', dish:'Paneer Pahadi Tikka', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Appetisers', dish:'Paneer Malai Tikka', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Appetisers', dish:'Paneer Achari Tikka', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Main Course', dish:'Paneer Reshmi Tikka', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Biryani', dish:'Paneer Hara Bhara Kabab', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Main Course', dish:'Corn Tikki', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    //     {foodType:'veg',cuisineType:'indian', category:'Appetisers', dish:'Mini Samosa', cost:'960', description:'40 pcs in 1 kg', imagepath:'../assets/img/dishes/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg '},
    // ]

    public static Dishes = 
   
    [
      {
        "dishId": 1,
        "dish": "Thai Spicy Roll",
        "description": "35-40 Pcs in 1 KG",
        "cost": "600",
        "foodType": "veg",
        "cuisineType": "chinese",
        "category": "Appetisers",
        "imagepath": "../../../assets/img/menu/Veg/Thai_Spicy_Roll_588b264c915ed.jpg",
        "itemVolumeType": "KG",
        "itemVolume": 1,
        "variationType": 0,
        "variation": "",
        "status": 1
      },
        {
          "dishId": 2,
          "dish": "Paneer Chilli",
          "description": "35-40 Pcs in 1 KG",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Chilli_588b24e958ed4.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },

        {
          "dishId": 3,
          "dish": "Mini Spring Roll",
          "description": "35-40 Pcs in 1 KG",
          "cost": "600",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Mini_Spring_Roll_588b26b1c152c.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 4,
          "dish": "Crispy Honey Potato",
          "description": "Crispy Honey Potato",
          "cost": "750",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Crispy_Honey_Potato_588b2747025b7.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 5,
          "dish": "Chili Basil Mushrooms",
          "description": "Chili Basil Mushrooms",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Chili_Basil_Mushrooms_588b28a3807f7.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 6,
          "dish": "Salt And Pepper Vegetable",
          "description": "Salt And Pepper Vegetable",
          "cost": "870",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Salt_And_Pepper_Vegetable_588b29762b9d5.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 8,
          "dish": "Chicken Chilli",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Chilli_588b2ac418b0f.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 9,
          "dish": "Shanghai Chicken",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Shanghai_Chicken_984c64de4.png",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 10,
          "dish": "Kung Pao Chicken",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Kung_Pao_Chicken_588b2f9c8d1e2.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 11,
          "dish": "Chicken Spring Roll",
          "description": "35-40 Pcs in 1 KG",
          "cost": "800",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Spring_Roll_588b30b66d024.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 12,
          "dish": "Chicken Lollipop",
          "description": "24 Pcs in 1 KG",
          "cost": "640",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Lollipop_588b313e28312.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 13,
          "dish": "Chicken Yakitori",
          "description": "35-40 Pcs in 1 KG",
          "cost": "1050",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Yakitori_588b325c10d218635.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 14,
          "dish": "Chicken Satay ",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Satay__588b339f9710d.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 15,
          "dish": "Prawns Chilli",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1000",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/_Chili_Garlic_Prawns__588b3479c7831.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 16,
          "dish": "Shanghai Prawns ",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1491",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Shanghai_Prawns__588b34e884533.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 17,
          "dish": "Fish Soya Chili",
          "description": "30-35 Pcs in 1 KG",
          "cost": "900-1050",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Soya_Chili_Fish__588b3533da452.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Basa,900|Ravas,1050",
          "status": 1
        },
        {
          "dishId": 19,
          "dish": "Fish Basil Tamarind",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1300",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Basil_Tamarind_Fish_588b35abc5903.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Basa,850|Ravas,1300",
          "status": 1
        },
        {
          "dishId": 25,
          "dish": "California Sushi Rolls ",
          "description": "48 Pcs in 1 KG",
          "cost": "1230",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Sushi",
          "imagepath": "../../../assets/img/menu/Veg/California_Sushi_Rolls__588b3b3ae9d64.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 26,
          "dish": "Cheese Cream Avocado Rolls ",
          "description": "48 Pcs in 1 KG",
          "cost": "1270",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Sushi",
          "imagepath": "../../../assets/img/menu/Veg/Cheese_Cream_Avocado_Rolls__588b3bb64cb3c.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 27,
          "dish": "Mango Sushi Rolls ",
          "description": "48 Pcs in 1 KG",
          "cost": "1140",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Sushi",
          "imagepath": "../../../assets/img/menu/Veg/Mango_Sushi_Rolls__588b3c069354a.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 29,
          "dish": "Burnt Garlic Fried Rice",
          "description": "** Weighed after Cooking",
          "cost": "600",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Burnt_Garlic_Fried_Rice_588c4d9fe6fb7.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 30,
          "dish": "Spicy Fried Rice",
          "description": "** Weighed after Cooking",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Spicy_Fried_Rice_588c4f33c42d6.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 31,
          "dish": "Hakka Noodles",
          "description": "** Weighed after Cooking",
          "cost": "600",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Hakka_Noodles_588c4f8133d4b3794.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 32,
          "dish": "Singapore Spicy Noodles",
          "description": "** Weighed after Cooking",
          "cost": "600",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Singapore_Spicy_Noodles_588c4fd7edbf4.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 33,
          "dish": "Malaysian Noodles",
          "description": "** Weighed after Cooking",
          "cost": "870",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Malaysian_Noodles_588c50333f565.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 34,
          "dish": "Pad Thai Noodles",
          "description": "** Weighed after Cooking",
          "cost": "900",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Pad_Thai_Noodles_588c5075e5e3e.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 35,
          "dish": "Burnt Garlic Fried Rice",
          "description": "** Weighed after Cooking",
          "cost": "730",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Non-Veg/Burnt_Garlic_Fried_Rice_588c51502a729.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 36,
          "dish": "Spicy Fried Rice",
          "description": "** Weighed after Cooking",
          "cost": "900",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Non-Veg/Spicy_Fried_Rice_588c519a16555.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "Chicken,900|Egg,850",
          "status": 1
        },
        {
          "dishId": 37,
          "dish": "Hakka Noodles",
          "description": "** Weighed after Cooking",
          "cost": "730",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Non-Veg/Hakka_Noodles_588c51c98c7fa.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 38,
          "dish": "Malaysian Noodles",
          "description": "** Weighed after Cooking",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Non-Veg/Malaysian_Noodles_588c5749ecdcf.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 39,
          "dish": "Pad Thai Noodles",
          "description": "** Weighed after Cooking",
          "cost": "950",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Non-Veg/Pad_Thai_Noodles_588c57852bd4c.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "Chicken,900|Egg,850",
          "status": 1
        },
        {
          "dishId": 41,
          "dish": "Paneer (Choice of Sauce)",
          "description": "35-40 Pcs in 1 KG",
          "cost": "1050",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_In_Shanghai_Sauce_588c597acfa49.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Black Bean|Hot Garlic|Hunan|Sichuan|Oyster",
          "status": 1
        },
        {
          "dishId": 43,
          "dish": "Chicken Thai Curry",
          "description": "Chicken Thai Curry Red",
          "cost": "1230",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Thai_Curry_Red_588c5a8bd9e6b.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Red|Yellow|Green",
          "status": 1
        },
        {
          "dishId": 44,
          "dish": "Thai Curry",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1300-1400",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Sea Food Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Prawns_Thai_Curry_Red_588c5aee6ba03.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 3,
          "variation": "Red|Yellow|Green-Fish,1300|Prawns,1400",
          "status": 1
        },
        {
          "dishId": 45,
          "dish": "Paneer Pahadi Tikka ",
          "description": "40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Pahadi_Tikka__588c6fa7e8f28.jpeg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 46,
          "dish": "Paneer Malai Tikka",
          "description": "40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Malai_Tikka_588c6fe7d6c9c.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 47,
          "dish": "Paneer Achari Tikka",
          "description": "40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Achari_Tikka_588c7032d21a08073.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 48,
          "dish": "Paneer Reshmi Tikka",
          "description": "25-30 Pcs in 1 KG",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Reshmi_Tikka_588c7086b4732.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 49,
          "dish": "Hara Bhara Kabab",
          "description": "35-40 Pcs in 1 KG",
          "cost": "750",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Hara_Bhara_Kabab_588c70d552558.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 50,
          "dish": "Corn Tikki",
          "description": "40 Pcs in 1 KG",
          "cost": "730",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Corn_Tikki_588c711ab50ff.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 51,
          "dish": "Mini Samosa",
          "description": "35-40 Pcs in 1 KG",
          "cost": "780",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Mini_Samosa_588c7150c509a.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 52,
          "dish": "Corn & Paneer Samosa",
          "description": "35 Pcs in 1 KG",
          "cost": "750",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Corn_&_Paneer_Samosa_588c71c29790f.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 53,
          "dish": "Paneer Tikka Kathi Roll",
          "description": "35-40 Pcs in 1 KG",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Tikka_Kathi_Roll_588c72171626c.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 54,
          "dish": "Tandoori Paneer ,Pineapple Tikka",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Tandoori_Paneer_,Pineapple_Tikka_588c72a98f777.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 55,
          "dish": "Paneer Fingers",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Fingers_588c72e0ce219.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 56,
          "dish": "Chicken Sholay Kabab",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Sholay_Kabab_588c737dd708f.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 57,
          "dish": "Chicken Alishan Kabab",
          "description": "30-36 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Alishan_Kaba_588c73e05ceb5.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 58,
          "dish": "Chicken Reshmi Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Reshmi_Tikka_588c747347393.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 59,
          "dish": "Chicken Lasooni Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Lasooni_Tikka_588c74a81584b.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 60,
          "dish": "Chicken Kalimiri Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Kalimiri_Tikka_588c74e9e8c39.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 61,
          "dish": "Chicken Chakori Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Chicken_Chakori_Tikka_588c75224d9f5.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 62,
          "dish": "Chicken Achari Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Chicken_Achari_Tikka_588c7559d0e74.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 63,
          "dish": "Chicken Tandoori",
          "description": "Chicken Tandoori ",
          "cost": "600",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Tandoori_588c79ca1d89e.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 64,
          "dish": "Chicken Tandoori-Lollipop",
          "description": "24 Pcs in 1 KG",
          "cost": "600",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Tandoori-Lollipop_588c7a193adfb.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 65,
          "dish": "Mutton Seekh Kabab",
          "description": "30-36 Pcs in 1 KG",
          "cost": "1365",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Mutton_Seekh_Kabab_588c7aa7e194b.jpeg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 67,
          "dish": "Chicken Malai Tikka",
          "description": "30-35 Pcs in 1 KG",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Malai_Tikka_588c7c00d708f.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 68,
          "dish": "Chicken Seekh Kabab",
          "description": "30-35 Pcs in 1 KG",
          "cost": "960",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Seekh_Kabab_588c7c481b0f15181.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 69,
          "dish": "Fish Koliwada",
          "description": "25-30 Pcs in 1 KG",
          "cost": "1540",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Fish_Koliwada_588c7d5df0614.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Rawas,1540|Basa,1050",
          "status": 1
        },
        {
          "dishId": 70,
          "dish": "Fish Tikka",
          "description": "30-36 Pcs in 1 KG",
          "cost": "1540",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Fish_Tikka_588c7dd5be43a.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Rawas,1540|Basa,1050",
          "status": 1
        },
        {
          "dishId": 71,
          "dish": "Prawns Koliwada",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1491",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Non-Veg/Prawns_Koliwada_588c7e11863c4.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 72,
          "dish": "Promfret Koliwada",
          "description": "Promfret Koliwada",
          "cost": "1400",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers Sea Food",
          "imagepath": "../../../assets/img/menu/Main/seafood_appetisers.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 73,
          "dish": "Veg Kadai",
          "description": "Veg Kadai",
          "cost": "700",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Veg_Kadai_588c8297a7f44.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 74,
          "dish": "Jeera  Aloo",
          "description": "Jeera  Aloo",
          "cost": "780",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Jeera__Aloo_588c83dcc2989.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 75,
          "dish": "Gobi Aloo",
          "description": "Gobi Aloo",
          "cost": "780",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Gobi_Aloo_588c8419c8c19.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 76,
          "dish": "Aloo Methi Chaman",
          "description": "Aloo Methi Chaman",
          "cost": "780",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Aloo_Methi_Chaman_588c846913aa9.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 77,
          "dish": "Mutter Mushroom",
          "description": "Aloo Methi Chaman",
          "cost": "750",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Mutter_Mushroom_588c84b5a61b96166.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 79,
          "dish": "Paneer",
          "description": "Paneer",
          "cost": "990",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_588c86dddd3f7.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Kadai|Butter Masala|Lababdar",
          "status": 1
        },
        {
          "dishId": 80,
          "dish": "Yellow Dal",
          "description": "Yellow Dal",
          "cost": "600",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Yellow_Dal_588c8757868fe.png",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Fry|Tadka",
          "status": 1
        },
        {
          "dishId": 81,
          "dish": "Dal Makhani",
          "description": "Dal Makhani",
          "cost": "870",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Dal_Makhani_588c878f7832f4661.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 82,
          "dish": "Amritsari  Chole",
          "description": "Amritsari  Chole",
          "cost": "870",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Amritsari__Chole_588c87ceebb6d3088.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 84,
          "dish": "Roasted Butter Chicken",
          "description": "Roasted Butter Chicken",
          "cost": "1050",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Butter_Chicken_588c884ebd57c5378.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 85,
          "dish": "Chicken Tariwala (With Bones)",
          "description": "Chicken Tariwala",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Tariwala_588c8883ac777.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 86,
          "dish": "Chicken Angara(With Bones)",
          "description": "Chicken Angara(With Bones)",
          "cost": "950",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Angara(With_Bones)_588c8929dea96.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 87,
          "dish": "Chicken Tikka Masala",
          "description": "Chicken Tikka Masala",
          "cost": "1150",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Tikka_Masala_588c89810e544.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 88,
          "dish": "Mutton Rogan Josh",
          "description": "Mutton Rogan Josh",
          "cost": "1150",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Mutton_588c89d1c933e.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 90,
          "dish": "Mutton Rarra",
          "description": "Mutton Rarra",
          "cost": "1300",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Mutton_Rarra_588c8ae043d49.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 91,
          "dish": "Mutton Keema",
          "description": "Mutton Keema",
          "cost": "1100",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Mutton_Keema_588c8b6f8a31a.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 92,
          "dish": "Fish Goan Curry",
          "description": "35-40 Pcs in 1 KG",
          "cost": "1405",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Sea Food Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Goan_Curry_588c8bda7b2ef.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Ravas,1540|Surmai,1405",
          "status": 1
        },
        {
          "dishId": 94,
          "dish": "Prawns",
          "description": "35-40 Pcs in 1 KG",
          "cost": "1491",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Sea Food Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Prawns_Kadai_588c8c709d8b5.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Kadai,1100|Goan Curry,1491",
          "status": 1
        },
        {
          "dishId": 95,
          "dish": "Veg Dum Biryani",
          "description": "** Weighed after Cooking",
          "cost": "850",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Veg/Veg_Dum_Biryani_598752ce678.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 96,
          "dish": "Paneer Tikka Biryani",
          "description": "** Weighed after Cooking",
          "cost": "1050",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Non-Veg/Paneer_Tikka_Biryani_588c8cff2db81.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 97,
          "dish": "Zafrani Pulao",
          "description": "** Weighed after Cooking",
          "cost": "915",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Non-Veg/Zafrani_Pulao_588c8dc82b8964041.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 98,
          "dish": "Chicken Dum Biryani(With Bones)",
          "description": "** 1KG of Raw Chicken",
          "cost": "1005",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Dum_Biryani(With_Bone)_588c8e800c0fe.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 99,
          "dish": "Chicken Tikka Biryani",
          "description": "** 1KG of Raw Chicken",
          "cost": "1180",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_Tikka_Biryani_588c8ecfd4a03.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 100,
          "dish": "Mutton Dum Biryani",
          "description": "** 1KG of Raw Mutton",
          "cost": "1300",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Non-Veg/Mutton_Dum_Biryani_588c8f2431946.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 101,
          "dish": "Roti",
          "description": "Roti",
          "cost": "25-35",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Roti_588c8f7866b9c.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,25|Butter,35",
          "status": 1
        },
        {
          "dishId": 102,
          "dish": "Naan",
          "description": "Naan",
          "cost": "30-40",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Naan_588c8facd7705.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,30|Butter,40",
          "status": 1
        },
        {
          "dishId": 103,
          "dish": "Kulcha",
          "description": "Kulcha",
          "cost": "35-45",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Kulcha_588c8fe984e69.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,35|Butter,45",
          "status": 1
        },
        {
          "dishId": 104,
          "dish": "Garlic Naan",
          "description": "Garlic Naan\r\n",
          "cost": "35-45",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Garlic_Naan_588c903031194.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,35|Butter,45",
          "status": 1
        },
        {
          "dishId": 105,
          "dish": "Stuffed Paratha",
          "description": "Stuffed Paratha",
          "cost": "40-50",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Stuffed_Paratha_588c906c460d7.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 3,
          "variation": "Onion|Aloo|Gobi|Mix-Plain,40|Butter,50",
          "status": 1
        },
        {
          "dishId": 106,
          "dish": "Paneer Paratha ",
          "description": "Paneer Paratha ",
          "cost": "50-60",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Paneer_Paratha__588c909ceb09f.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,50|Butter,60",
          "status": 1
        },
        {
          "dishId": 107,
          "dish": "Cheese Garlic Naan",
          "description": "Cheese Garlic Naan",
          "cost": "55-65",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Breads",
          "imagepath": "../../../assets/img/menu/Veg/Cheese_Garlic_Naan_588c90dfa4b57.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 1,
          "variationType": 2,
          "variation": "Plain,55|Butter,65",
          "status": 1
        },
        {
          "dishId": 108,
          "dish": "Seasonal Fruit Souflle",
          "description": "Seasonal Fruit Souflle",
          "cost": "840",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Desserts",
          "imagepath": "../../../assets/img/menu/Veg/Seasonal_Of_Fruit_Souflle_588c914803efd.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 109,
          "dish": "Moong Dal Halwa",
          "description": "Moong Dal Halwa",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Desserts",
          "imagepath": "../../../assets/img/menu/Veg/Moong_Dal_Halwa_588c917a6b11b.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 110,
          "dish": "Gajar Halwa",
          "description": "Gajar Halwa",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Desserts",
          "imagepath": "../../../assets/img/menu/Veg/Gajar_Halwa_588c91c0483a1.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 111,
          "dish": "Gulab Jamun",
          "description": "Gulab Jamun",
          "cost": "300",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Desserts",
          "imagepath": "../../../assets/img/menu/Veg/Gulab_Jamun_588c91f3520e5.jpg",
          "itemVolumeType": "Pcs",
          "itemVolume": 12,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 112,
          "dish": "Vegetable Thai Curry",
          "description": "Vegetable Thai Curry",
          "cost": "1230",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Vegetable_Thai_Curry_588c950275bec.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Red|Yellow|Green",
          "status": 1
        },
        {
          "dishId": 113,
          "dish": "Vegetables (Choice of Sauce)",
          "description": "Exotic Veg",
          "cost": "1050",
          "foodType": "veg",
          "cuisineType": "chinese",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Exotic_Veg_588c956e3faad.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Black Bean|Hot Garlic|Hunan|Sichuan|Oyster",
          "status": 1
        },
        {
          "dishId": 114,
          "dish": "Chicken (Choice of Sauce)",
          "description": "35-40 Pcs in 1 KG",
          "cost": "1050",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chicken_588c95c85bad63478.png",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Black Bean|Hot Garlic|Hunan|Sichuan|Oyster",
          "status": 1
        },
        {
          "dishId": 115,
          "dish": "Tandoori Platter",
          "description": "35-40 Pcs in 1 KG",
          "cost": "960",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Veg/Tandoori_Platter_588c971e8f03d.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Mushroom|Baby Corn|Baby Potato|Gobi",
          "status": 1
        },
        {
          "dishId": 116,
          "dish": "Pulao",
          "description": "** Weighed after Cooking",
          "cost": "870",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Biryani",
          "imagepath": "../../../assets/img/menu/Veg/Pulao_588c9d2a08164.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "GreenPeas|Pilaf|Veg",
          "status": 1
        },
        {
          "dishId": 117,
          "dish": "Fish (Choice of Sauce)",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1200",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Sea Food Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Fish_588c9f8879972.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Black Bean|Hot Garlic|Hunan|Sichuan|Oyster",
          "status": 1
        },
        {
          "dishId": 118,
          "dish": "Prawns (Choice of Sauce)",
          "description": "30-35 Pcs in 1 KG",
          "cost": "1491",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Sea Food Main Course",
          "imagepath": "../../../assets/img/menu/Non-Veg/Prawns_588c9fb4e6396.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 1,
          "variation": "Black Bean|Hot Garlic|Hunan|Sichuan|Oyster",
          "status": 1
        },
        {
          "dishId": 119,
          "dish": "Singapore Spicy Noodles",
          "description": "** Weighed after Cooking",
          "cost": "730",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Rice And Noodles",
          "imagepath": "../../../assets/img/menu/Veg/Singapore_Spicy_Noodles_588c4fd7edbf4.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 120,
          "dish": "Tandoori Platter",
          "description": "30-35 Pcs in 1 KG",
          "cost": "990",
          "foodType": "non-veg",
          "cuisineType": "indian",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Tandoori_Platter_5927e51842040.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 121,
          "dish": "Steam Rice",
          "description": "1 KG serves approx 8 -10 people",
          "cost": "420",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Steam_Rice_5927e5ebbc4d1.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 122,
          "dish": "Jeera Rice",
          "description": "1 KG serves approx 8 -10 people",
          "cost": "550",
          "foodType": "veg",
          "cuisineType": "indian",
          "category": "Main Course",
          "imagepath": "../../../assets/img/menu/Veg/Jeera_Rice_5927e695f3387.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 1
        },
        {
          "dishId": 123,
          "dish": "Grilled Chicken Black Bean",
          "description": "Grilled Chicken Black Bean",
          "cost": "850",
          "foodType": "non-veg",
          "cuisineType": "chinese",
          "category": "Appetisers",
          "imagepath": "../../../assets/img/menu/Non-Veg/Grilled_Chicken_Black_Bean_5927e7ea12d83.jpg",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 124,
          "dish": "Chargrilled Norwegian Salmon Tikka",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Chargrilled_Norwegian_Salmon_Tikka_59378b84d887f.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 125,
          "dish": "Amritsari Tawa Salmon",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Amritsari_Tawa_Salmon_59378bff02f26.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 126,
          "dish": "Bengali Yoghurt Mustard Salmon",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Bengali_Yoghurt_Mustard_Salmon_59378c6619390.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 127,
          "dish": "Norwegian Salmon Coconut Malai Curry",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Norwegian_Salmon_Coconut_Malai_Curry_59378cb33433b.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 128,
          "dish": "Vindaloo Glazed Salmon",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Vindaloo_Glazed_Salmon_59378cf043dd6.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 129,
          "dish": "Smoked Norwegian Salmon Sandwich with Scrambled Egg",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Smoked_Norwegian_Salmon_Sandwich_with_Scrambled_Egg_59378d6063f27.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 130,
          "dish": "Smoked Norwegian Salmon with Rice Salad",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Smoked_Norwegian_Salmon_with_Rice_Salad_593793a749ca2.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        },
        {
          "dishId": 131,
          "dish": "Norwegian Salmon Kebab with Coriander Yoghurt",
          "description": "",
          "cost": "1500",
          "foodType": "non-veg",
          "cuisineType": "Chef Special",
          "category": "Chef Saby",
          "imagepath": "../../../assets/img/menu/Non-Veg/Norwegian_Salmon_Kebab_with_Coriander_Yoghurt_5937942d11e88.PNG",
          "itemVolumeType": "KG",
          "itemVolume": 1,
          "variationType": 0,
          "variation": "",
          "status": 2
        }
      ]

}
